### ISSUE TITLE
new owner

### ISSUE THREAD

**Issue by logicminds** [drwahl/puppet-git-hooks#100]
Hey I think you should give this to vox-pupuli since you are looking for a new owner.

https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli

**Comment by jhg03a** [comment]
Already tracked in #59

**Comment by pillarsdotnet** [comment]
Can this issue be closed?
@drwahl ?
@krzyzakp ?

**Comment by drwahl** [comment]
Ya, I think my part time management of this project along with the help @krzyzakp has been providing should be sufficient.
