### ISSUE TITLE
git push results in "couldn't find HOME environment"

### ISSUE THREAD

**Issue by kostyrevaa** [drwahl/puppet-git-hooks#12]
remote: Checking puppet manifest syntax for manifests/VMs/pinba.caravan.dmz.pp...
remote: Error: Could not initialize global default settings: couldn't find HOME environment -- expanding `~/.puppet'
remote: Error: puppet syntax error in manifests/VMs/pinba.caravan.dmz.pp (see above)
remote: Error: 1 syntax error(s) found in puppet manifests. Commit will be aborted.
remote: puppet-lint not installed. Skipping puppet-lint tests...
remote: Error: 1 subhooks failed. Declining push.

**Comment by drwahl** [comment]
Based on the last comment, I'm guessing this might be resolved.  Feel free to reopen if this is still causing issues.
