### ISSUE TITLE
error with module in autoload format

### ISSUE THREAD

**Issue by mmarseglia** [drwahl/puppet-git-hooks#16]
Hi,

  I'm using gitlab and the check is throwing an erroneous 'module not in autoload format' error.  When I test on my local machine I do not get the autoload error.  I'm not sure what the difference is between checking the file on gitlab and checking on my local machine.  Could you please provide some insight as to what may be happening?

**Comment by drwahl** [comment]
That error is technically coming from puppet-lint.  Here's their documentation on this:
http://puppet-lint.com/checks/autoloader_layout/

I can't say for sure, but I suspect that on the hooks on your gitlab server may not be pointing to quite the right location for their --module-path.  If this information doesn't help you track down the issue, let me know and we can try some deeper troubleshooting.

**Comment by mmarseglia** [comment]
thank you, i will look at that.

**Comment by juasiepo** [comment]
I am having the same problem but instead Gitlab I am using gitolite

**Comment by drwahl** [comment]
For what it's worth, I developed these hooks with a gitolite backend and then eventually migrated them to a GitLab backend.  So I have had success using these hooks with both of these services.

**Comment by mmarseglia** [comment]
do you have all your modules in a single repo?  I have one module per repository. so my manifest path ends up looking like this:
`/tmp/tmp.<random string>/manifests/init.pp`

**Comment by drwahl** [comment]
I do have all my modules in a single repo.  I know this isn't necessarily best practice, but it is our current workflow.  I don't see why these hooks couldn't be modified to work with that workflow as well, but some more logic would need to be added for them to know how to find everything.

**Comment by juasiepo** [comment]
I have the same configuration as @mmarseglia so some logic must to be added in order add this feature. In the mean time have disabled this feature with the **--no-autoloader_layout-check** parameter in the puppet_lint_checks.sh file

**Comment by LaurencelleJ** [comment]
I hit the same issue.  The name of the tmp directory is being passed as the module_path.  If you manually run lint against that file structure you get the autoloader error.  If you change the name of the tmp.xxxxx directory to your module name lint passes. Seams like the tmp directory should be something like /tmp/tmp.xxx/reponame/ (assuming you have one module/repo).

**Comment by drwahl** [comment]
Ya, the issue here is that some workflows have all modules in a single repo while other workflows have one repo per module.  I don't have a good suggestion on how to handle this yet, but I'm ears if anyone has any ideas.

**Comment by mrjoshuap** [comment]
@juasiepo You can specify those options in a `.puppet-lint.rc` file next to your `.gitignore` and `.gitattributes` files.  I keep one that looks like:

    --no-autoloader_layout-check
    --no-class_inherits_from_params_class-check
    --no-80chars-check

Your mileage may vary, but it allows me to customize it between modules and not have to worry about upstream changes.

**Comment by janfabry** [comment]
If only the top directory is different, you can add the `--relative` parameter, added in 1.0.0 for this situation:

> Added `--relative` flag which will have the `autoloader_layout` check ignore the top-most directory (good for cases where the module hosted publicly in a `puppet-<foo>` directory).

I have added this in my local install, do you see any drawbacks including it in the main version?

**Comment by drwahl** [comment]
This seems like an elegant solution.  Feel free to make a PR if you have the code handy.  Otherwise, I'll look at getting something added soon(tm).
