### ISSUE TITLE
add future parser support

### ISSUE THREAD

**Issue by logicminds** [drwahl/puppet-git-hooks#41]
manifests that use the future parser fail the manifest validation.  

https://github.com/drwahl/puppet-git-hooks/blob/master/commit_hooks/puppet_manifest_syntax_check.sh#L23

**Comment by logicminds** [comment]
should be something like `puppet parser --parser=future validate path_to_manifest`

**Comment by jschlyter** [comment]
ref: https://github.com/drwahl/puppet-git-hooks/pull/42

**Comment by logicminds** [comment]
Now the opposite effect occurs.  So when the 4.x puppet is used it errors about invalid parser=future option.

We will need to detect which version exists and then use the version specific command.   Or just allow the user to configure this.

**Comment by jschlyter** [comment]
I've updated https://github.com/drwahl/puppet-git-hooks/pull/42 to enable the future parser only for Puppet 3.7.x and 3.8.x, please test.

**Comment by jhg03a** [comment]
I've made the future parser optional entirely in case you're on version 4 or have no interest in it with PR #45.

**Comment by jschlyter** [comment]
Perfect!

**Comment by rvincentatprokarmadotcom** [comment]
This issue should be closed as "fixed".

**Comment by krzyzakp** [comment]
It's fixed since long time, so closing.
