### ISSUE TITLE
post-commit server side hooks

### ISSUE THREAD

**Issue by smbambling** [drwahl/puppet-git-hooks#56]
I have written a server side post-commit git-hook that will trigger the code-manager in Puppet Enterprise 2015.3+.  I'd like to add support for post-commit hooks but want guidance on consistency with this module

1. Do you have an issue with using multiple languages for hooks?
2. Do you have an issue with hooks requiring dependent modules ?
  - My current hook requires the python-request module
3. Would you like the deploy-git-hook updated to also 'publish' the hook, I can add an option to be able to select a specific hook to push.

**Comment by jhg03a** [comment]
Not an admin, but...
1. Yes, adding languages makes more dependency problems.
2. Yes, see above.  Specific checks are already externalized in the commit_hooks folder.
3. Not sure I follow the question.  There exists mechanisms to enable/disable each check in the hooks I believe already.

**Comment by smbambling** [comment]
@jhg03a:  For number 3, there may we several different post-commit hooks that users would want triggered.  Some examples R10k, Code-Manager, Simple Email Notification....

So extended the script to allow one to select a post-commit hook to 'install' or link sounds like it would help with that issue.

Noted in 1/2...I have a mostly complete re-write in bash, I just didn't want to continue if it wasn't going to be used.

**Comment by smbambling** [comment]
I'll look at trying to follow something similar whats listed below for any dependancies that might be needed.

```
ruby -e "require 'yaml'; YAML.parse(File.open('$1'))" 2> $error_msg > /dev/null
```
