### ISSUE TITLE
Add Maintainers by moving to https://github.com/voxpupuli formally Puppet Community

### ISSUE THREAD

**Issue by smbambling** [drwahl/puppet-git-hooks#59]
If you don't have cycles or are unable to maintain this project anymore you can always look at moving it to https://github.com/voxpupuli

**Comment by drwahl** [comment]
That's a great idea. Thanks! I'll be moving this repo there next.

**Comment by smbambling** [comment]
Cool, sorry for creating the issue...I couldn't find any other contact info for you.

**Comment by rnelson0** [comment]
Hi @drwahl. It was brought to my attention you might want VP to adopt this repo. If that is still your plan, we don't have a specific document for tools, but you can copy our [module migration checklist](https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli) into an issue and then [contact us](https://voxpupuli.org/docs/#where-you-can-find-us) to start the process. Thanks!

**Comment by sambanks** [comment]
Hi @drwahl did you ever get a maintainer? I would be happy to take it over if not.
Cheers
Sam

**Comment by drwahl** [comment]
Hi @sambanks. I have found another person to collaborate with on maintaining these hooks.  Should we need additional help, I'll reach out to you.

**Comment by sambanks** [comment]
Great news!

**Comment by pillarsdotnet** [comment]
Since @drwahl  has found "another person to collaborate with," who seems to be @krzyzakp judging by recent pull-request approvals, we should [update the README.md accordingly](https://github.com/drwahl/puppet-git-hooks/pull/101).

**Comment by pillarsdotnet** [comment]
Also, this issue (and related #100) should be closed.

**Comment by krzyzakp** [comment]
Closing same as #100 as David decided there.
