### ISSUE TITLE
--no-80chars-check breaks latest puppet-lint code

### ISSUE THREAD

**Issue by walkamongus** [drwahl/puppet-git-hooks#72]
I just installed puppet-lint from the latest code on github. It looks like they changed the default line-length check to 140 chars and removed the 80-chars check altogether. This means keeping it as a default in puppet_lint_checks.sh causes puppet-lint to just error out.

I propose removal of this default. It can be easily added in via .puppet-lint.rc or in config.cfg for those who want the check and this default will have to be removed or changed when the next version of puppet-lint is released anyway. Removing the default will not break older puppet-lint versions and will allow new version to work without modification.

I can submit a PR if others agree.

**Comment by samuraiii** [comment]
I can confirm that with puppet-lint 2.0.0

**Comment by anders-larsson** [comment]
I can confirm it as well. Happens with puppet-lint 2.0.0.

**Comment by krzyzakp** [comment]
I updated code, added dependency to new puppet-lint and documented it, so now new puppet-lint will be used.
