### ISSUE TITLE
GitLab merge requests through GUI fails with this hook enabled

### ISSUE THREAD

**Issue by divansantana** [drwahl/puppet-git-hooks#76]
Due to GitLab issue [here](https://gitlab.com/gitlab-org/gitlab-ce/issues/13473) and [here](https://gitlab.com/gitlab-org/gitlab-ce/issues/4152) when this puppet-git-hook is installed in GitLab, one can't merge MRs through the web GUI.

Setting this in the [pre-receive](pre-receive) file resolves the issue.
```bash
unset BUNDLE_GEMFILE RUBYLIB RUBYOPT GEM_HOME
```

@drwahl are you happy to accept a MR with this set at the top of the [pre-receive](pre-receive) file? I wouldn't think it would negatively effect other VCS systems.

@jharlow1 you may find this of interest too.

**Comment by drwahl** [comment]
Ya, I can't see why that would cause problems. If no one else chimes in on this, I would love to see a PR.

**Comment by jharlow1** [comment]
Only thought here is that I'd maybe wrap it in a config flag just in case it screws someone else's environment up, but it should be benign in the majority of cases, I'd think.

**Comment by divansantana** [comment]
Cool. Thanks for the input. I'll submit a PR tomorrow.

**Comment by divansantana** [comment]
PR done.
