### ISSUE TITLE
Initial commit always results in bad object and puppet-lint not found

### ISSUE THREAD

**Issue by danjng** [drwahl/puppet-git-hooks#8]
Everything is fine and I'm using the hooks in the right places.  I'm able to clone the repo, but when I do my first commit to put files up there, I get the following error:
"remote: fatal: bad object 0000000000000000000000000000000000000000"

I'm using the pre-receive hook.

Despite the error, my content is still pushed up.  However, none of the syntax is actually checked.

If I make changes and do a subsequent commit, it WILL check for the syntax, but it will ALSO say that it can't find puppet-lint (not sure what to make of this).

"Total 4 (delta 2), reused 0 (delta 0)
remote: Checking puppet manifest syntax for manifests/init.pp...
remote: puppet-lint not installed. Skipping puppet-lint tests..."

puppet-lint is definitely installed because it is used in the initial check. 

Thoughts?

**Comment by drwahl** [comment]
This should be addressed with ffbd703dfccd3ca6ed55efa6adfe3efe97b33d74.  Please give this patch a shot and reopen this issue if you are still seeing the same symptom.
