### ISSUE TITLE
r10k incorrect basedir being used with PUPPETFILE environment variable

### ISSUE THREAD

**Issue by jhg03a** [drwahl/puppet-git-hooks#80]
I ran into a problem today where the PUPPETFILE environment variable wasn't being applied correctly on Ubuntu 14.04 x64 using the r10k gem version 2.2.2.

https://tickets.puppetlabs.com/browse/RK-165

**Comment by redno2** [comment]
I'am also affected without set the PUPPETFILE env.
Ubuntu 14.04 x64 - r10k 2.2.0

$ git push
remote: Performing a syntax check on the r10k Puppetfile:
remote: No such file or directory @ rb_sysopen - /PATH_TO_BAR_GIT_REPO/Puppetfile

**Comment by krzyzakp** [comment]
This seems more like puppet error than our script itself. Especially that error is also coming from r10k, so nothing we could fix directly on our side unfortunately.
