### ISSUE TITLE
Typo in puppet_lint_checks.sh

### ISSUE THREAD

**Issue by pabohoney1** [drwahl/puppet-git-hooks#87]
There's a typo in puppet_lint_checks.sh, line 60, you have an extra 's' at the end of the line:

echo -e "$(tput setaf 1)Error: styleguide violation in $manifest_name (see above)$(tput sgr0)"s

**Comment by krzyzakp** [comment]
Thanks for spotting it. Must be leftover from changes which I did on that they. Fixed directly in master.
